services:
  psql_database:
    container_name: psql_database
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - psqldb:/var/lib/postgresql@16.3/data

  mongo_database:
    container_name: mongo_database
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_db:/data/db

  mongo_express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    depends_on:
      - mongo_database
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
volumes:
  psqldb:
  mongodb_db:
